server:
  port: 8080
  servlet:
    context-path: /api
minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin    # 如果你修改过请改这里
  secretKey: minioadmin
  bucket: weicanjie
spring:
  application:
    name: weicanjie-system
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weicanjie_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

#  # Redis配置
#  redis:
#    host: localhost
#    port: 6379
#    database: 0
#    timeout: 3000ms
#    lettuce:
#      pool:
#        max-active: 20
#        max-wait: -1ms
#        max-idle: 8
#        min-idle: 0

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 日志配置
logging:
  level:
    com.restaurant: debug
    org.springframework.web: info